# lua 5.1.5

set(ENV{LUA_DIR} ${LIBLUA_DIR})
IF (CMAKE_CROSSCOMPILING)
find_package(Lua)
ELSE()
find_package(Lua REQUIRED)
ENDIF()

IF(WIN32)

set(TEMP_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
set(CMAKE_FIND_LIBRARY_SUFFIXES ".dll")

find_library(LUA_DLL
    NAMES lua5.1
    PATHS ${LIBLUA_DIR}/lib/Release ${LIBLUA_DIR}/lib
    NO_DEFAULT_PATH)
mark_as_advanced(LUA_DLL)

set(CMAKE_FIND_LIBRARY_SUFFIXES ${TEMP_SUFFIXES})
unset(TEMP_SUFFIXES)

ENDIF()

message("LUA_VERSION_STRING: " ${LUA_VERSION_STRING})
message("LUA_INCLUDE_DIR: " ${LUA_INCLUDE_DIR})
message("LUA_LIBRARY: " ${LUA_LIBRARY})

IF(WIN32)
message("LUA_DLL: " ${LUA_DLL})
ENDIF()

IF(NOT LUA_VERSION_STRING STREQUAL "5.1.5")
    message(FATAL_ERROR "Lua version error")
ENDIF()
message("")
